### ISSUE TITLE
新渠道支持

### ISSUE THREAD

**Issue by lljxx1** [wechatsync/Wechatsync#1]
- 豆瓣日记
- 开源中国
- 百度百家
- 新浪看点
- 大鱼号
- 搜狐
- Ghost

**Comment by lljxx1** [comment]
计划新增
- Ghost
- 豆瓣日记

**Comment by lljxx1** [comment]
豆瓣
- 编辑器darftjs
- 格式相对标准
- 需要html turndown转markdown然后转draftjs

**Comment by Lan-ce-lot** [comment]
请教一下，现在支持ghost了吗？
