### ISSUE TITLE
添加渠道账号一直显示空白

### ISSUE THREAD

**Issue by YummyLau** [wechatsync/Wechatsync#15]
比如无法添加掘金等渠道。

**Comment by lljxx1** [comment]
最好带上截图，是页面UI空白 还是无法识别到掘金账号？

**Comment by lljxx1** [comment]
另外打开扩展的【详细信息】
请确保:
![image](https://user-images.githubusercontent.com/7993835/100427789-f1515400-30cd-11eb-8a08-f32e9c08c1d4.png)

**Comment by YummyLau** [comment]
@lljxx1 确保是所有网站，就是点击掘金账号之后
![1606466088730](https://user-images.githubusercontent.com/4456538/100428146-83595c80-30ce-11eb-9042-b93fd9d842ab.jpg)

**Comment by lljxx1** [comment]
@YummyLau 想起来了掘金是有点bug，正常是会自动识别账号的
