### ISSUE TITLE
[Feature Request] Markdown 发布可以支持 Typecho 吗？

### ISSUE THREAD

**Issue by LucienShui** [wechatsync/Wechatsync#19]

**Comment by lljxx1** [comment]
大概可以，但是html转markdown的效果可能不一定好

**Comment by LucienShui** [comment]
好的吧，对我个人而言，我会在 Typecho 和 CSDN 上发文，所以我的需求是一个能够将 Markdown 同步到两个平台的工具。

如果作者大大认为 HTML 转 Markdown 效果会不好的话，那我觉得是没有必要硬做的。

我会再寻找一下其它工具的，感谢作者大大。

**Comment by lljxx1** [comment]
你的主发布平台如果是微信公众号会有html转markdown的问题，
另外我有打算提供一个以markdown编辑器 出发再同步到多个平台平台（CSDN，公众号，Typecho）的方案

**Comment by lljxx1** [comment]
这个有用过吗
https://www.wechatsync.com/md/

**Comment by LucienShui** [comment]
> 这个有用过吗
> https://www.wechatsync.com/md/

没有诶，我试试看。

**Comment by LucienShui** [comment]
> 你的主发布平台如果是微信公众号会有html转markdown的问题，
> 另外我有打算提供一个以markdown编辑器 出发再同步到多个平台平台（CSDN，公众号，Typecho）的方案

是 https://www.wechatsync.com/md/ 这个网址是吗？

**Comment by LucienShui** [comment]
好的，非常期待！功能 Ready 了之后烦请通知我！谢谢大佬。
