### ISSUE TITLE
简书的排版错乱

### ISSUE THREAD

**Issue by TANZAME** [wechatsync/Wechatsync#37]
这是在编辑器的预览效果
![image](https://user-images.githubusercontent.com/7043207/123820159-f0ff8c80-d92c-11eb-8263-756d162de085.png)

但是到简书却成了这样。。。
![image](https://user-images.githubusercontent.com/7043207/123820412-27d5a280-d92d-11eb-9e65-6f00fd5db624.png)
![image](https://user-images.githubusercontent.com/7043207/123820478-34f29180-d92d-11eb-95b8-ebc59f05c7af.png)

**Comment by WeihanLi** [comment]
可能是因为简书的默认编辑器设置的是 markdown，换成富文本试一下
