### ISSUE TITLE
b站和知乎 图片传不上去，简书在编辑器里面图片显示，但是发布之后为不显示

### ISSUE THREAD

**Issue by JACK-ZHANG-coming** [wechatsync/Wechatsync#38]
b站和知乎 图片传不上去，简书在编辑器里面图片显示，但是发布之后为不显示，其一图片链接如下：![image-20210616213753355(https://i.loli.net/2021/07/18/Bz95UFDrn4VAm6Y.png)

**Comment by JACK-ZHANG-coming** [comment]
使用知乎自带的“文档导入”功能是可以正常导出的，
![image](https://user-images.githubusercontent.com/44993003/126092859-03164737-204b-4320-bec7-38162cc283ad.png)

**Comment by lljxx1** [comment]
貌似是图床链接GET请求返回的是HTML的原因？
