### ISSUE TITLE
请问是否添加账号有什么要求

### ISSUE THREAD

**Issue by waney** [wechatsync/Wechatsync#40]
请问是否支持localStorage存储用户信息的站点。

**Comment by lljxx1** [comment]
wordpress和typecho会存在localStorage里
其他平台都即检查即用
你是要开发适配器 ，需要用户信息存储API对吧？
之前考虑适配器可以提供个form表单，用户可以根据这些字段输入信息，
在初始化适配器的时候注入这些用户信息

**Comment by waney** [comment]
是的，目标网站用户信息是存在localStorage里的，还有前端加密提交，验证码。

**Comment by lljxx1** [comment]
加密有CryptoJS
验证码估计即得自己搞API去打码了
存储这个我看看提供一个机制

**Comment by waney** [comment]
```
new TransCode();
```
很讨厌的。
