### ISSUE TITLE
希望能支持思否，掘金

### ISSUE THREAD

**Issue by zaunist** [wechatsync/Wechatsync#44]
现在浏览器插件好像不能识别到思否登录的账号

**Comment by zaunist** [comment]
系统：macOS big sur 11.6   
chrome 版本： 93.0.4577.82（正式版本） (x86_64)    
插件版本：1.0.10
内核版本：0.0.13

**Comment by lljxx1** [comment]
收到 可能失效了

**Comment by iswbm** [comment]
@lljxx1 
请问这个还没有修复吗？半年了哈哈，特意来找这个 issue
