### ISSUE TITLE
希望增加到notion里，notion很多插件都没有办法完整复制

### ISSUE THREAD

**Issue by huaaahua** [wechatsync/Wechatsync#55]

**Comment by curly210102** [comment]
是指从 notion 发布内容？

**Comment by huaaahua** [comment]
就是把公众号文章复制保存到notion里，现在微信公众号没有办法直接复制了，很多插件也只能把公众号文章的网页链接复制保存，但是完整的内容无法保存，然后我发现您这个插件很有用，可以完整复制图片文字，但是希望增添一个可以复制保存到notion的功能，不知道是否有可能🤔

Curly Brackets ***@***.***>于2021年12月8日 周三21:44写道：

**Comment by linonetwo** [comment]
剪藏用 [https://github.com/webclipper/web-clipper/](https://github.com/webclipper/web-clipper/) 啊

**Comment by huaaahua** [comment]
谢谢，之前用的都是notion web clipper ，总是剪藏不了，感谢

lin onetwo ***@***.***> 于2021年12月15日周三 10:50写道：
