### ISSUE TITLE
使用网页提取文章功能的时候发现了一个bug

### ISSUE THREAD

**Issue by qiudong19901008** [wechatsync/Wechatsync#57]
![20220102213442-2022-01-02-21-34-43](https://wpp.w2fenx.com/w2fenx/20220102213442-2022-01-02-21-34-43.png)

![20220102213332-2022-01-02-21-33-32](https://wpp.w2fenx.com/w2fenx/20220102213332-2022-01-02-21-33-32.png)

![20220102213400-2022-01-02-21-34-01](https://wpp.w2fenx.com/w2fenx/20220102213400-2022-01-02-21-34-01.png)

![20220102213426-2022-01-02-21-34-26](https://wpp.w2fenx.com/w2fenx/20220102213426-2022-01-02-21-34-26.png)

使用提取文章功能的时候发现了一个bug, 当文章含有\<pre\>\<code\>时, 只会提取\<pre\>\<code\>的内容

**Comment by lljxx1** [comment]
目前用的是safari提取正文的代码 不好处理
