### ISSUE TITLE
注册流程体验优化

### ISSUE THREAD

**Issue by renyuzhuo** [wechatsync/Wechatsync#7]
注册过程，由于密码输入不符合规范，填写了多次，符合要求后又提示我注册过于频繁，有待优化。

- 可以考虑不规范的密码格式现在本地校验，符合要求再提交服务器，或注册按钮置灰不允许提交（置灰的同时需要不符合规范的输入框标红提示）

- 提交完这个 Issue 后依旧提示我注册频繁，中间已经过去了一段时间，怀疑是否提示错误。

<img width="424" alt="截屏2020-09-08 上午12 33 51" src="https://user-images.githubusercontent.com/7275046/92406880-bcd39900-f16b-11ea-864f-384e58f4e15e.png">

**Comment by lljxx1** [comment]
这个用的第三方

**Comment by lljxx1** [comment]
给他们反馈了
