### ISSUE TITLE
微信公众号，同步失败

### ISSUE THREAD

**Issue by 1551255004** [wechatsync/Wechatsync#79]
<img width="612" alt="Snipaste_2022-12-17_16-40-06" src="https://user-images.githubusercontent.com/66911217/208233692-ea4e51bc-03d7-4c5e-b8c1-95defe2f7855.png">
插件版本：1.013

**Comment by YanZhao1** [comment]
请问一下修复后有编译后的最新版本吗？

**Comment by YanZhao1** [comment]
> 请问一下修复后有编译后的最新版本吗？

能不能把商店的更新一下

**Comment by KJZH001** [comment]
同样的错误
>同步失败, 错误内容：Error: 同步失败 错误内容：系统繁忙，请稍后重试
chrome商店和zip开发者模式安装都试过了
不过奇怪的是，虽然确实没有同步过去，但是图片成功传上去了....

**Comment by KJZH001** [comment]
忽然发现这已经是去年的issue了，而且最后一次commit是在22年
感觉或许停止维护了？

**Comment by zjh1943** [comment]
同样的问题
